//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LuxTravelEntities : DbContext
    {
        public LuxTravelEntities()
            : base("name=LuxTravelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking_Status> Booking_Status { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<Guest> Guests { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<Payment_Status> Payment_Status { get; set; }
        public virtual DbSet<Payment_Types> Payment_Types { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Rate_Types> Rate_Types { get; set; }
        public virtual DbSet<ReservationAgent> ReservationAgents { get; set; }
        public virtual DbSet<Room_Booked> Room_Booked { get; set; }
        public virtual DbSet<Room_Status> Room_Status { get; set; }
        public virtual DbSet<Room_Types> Room_Types { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Staff_Rooms> Staff_Rooms { get; set; }
        public virtual DbSet<Star_Ratings> Star_Ratings { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Ward> Wards { get; set; }
        public virtual DbSet<CityDistrictMapping> CityDistrictMappings { get; set; }
        public virtual DbSet<DistrictWardMapping> DistrictWardMappings { get; set; }
        public virtual DbSet<HotelLocation> HotelLocations { get; set; }
        public virtual DbSet<ImageStore> ImageStores { get; set; }
        public virtual DbSet<Rate> Rates { get; set; }
    }
}
