//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room_Booked
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> Booking_Id { get; set; }
        public Nullable<System.Guid> Room_Id { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
    
        public virtual Booking Booking { get; set; }    
        public virtual Room Room { get; set; }
    }
}
